apiVersion: apps/v1
kind: Deployment
metadata:
  name: voter-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voter
  template:
    metadata:
      labels:
        app: voter
    spec:
      containers:
      - name: python-voter
        image: poll-app:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          value: "host.docker.internal"
        - name: REDIS_PORT
          value: "7001"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: voter-service
spec:
  type: LoadBalancer
  selector:
    app: voter
  ports:
    - port: 80
      targetPort: 5000